apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835-final-project
  region: "us-east-1"
  version: "1.29"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

iam:
  serviceRoleARN: arn:aws:iam::626108377158:role/LabRole

managedNodeGroups:
  - name: clo835-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    iam:
      instanceRoleARN: arn:aws:iam::626108377158:role/LabRole
    ssh:
      enableSsm: true
