apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
        - name: flask-app
          image: 626108377158.dkr.ecr.us-east-1.amazonaws.com/clo835-final-project:latest
          ports:
            - containerPort: 81
          env:
            - name: DBHOST
              value: "mysql-service"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DATABASE
              value: "employees"
            - name: DBPORT
              value: "3306"
            - name: BACKGROUND_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKGROUND_IMAGE_URL
            - name: MY_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MY_NAME

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
